#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef WHALECLOUD_SWIFT_H
#define WHALECLOUD_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WhaleCloud",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSStream;

SWIFT_CLASS("_TtC10WhaleCloud16FoundationStream")
@interface FoundationStream : NSObject <NSStreamDelegate>
- (void)stream:(NSStream * _Nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10WhaleCloud7GamePad")
@interface GamePad : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(uint16_t, GamePadBtnKey, open) {
  GamePadBtnKeyBTN_A = 0x1000,
  GamePadBtnKeyBTN_B = 0x2000,
  GamePadBtnKeyBTN_X = 0x4000,
  GamePadBtnKeyBTN_Y = 0x8000,
  GamePadBtnKeyBTN_LB = 0x0100,
  GamePadBtnKeyBTN_RB = 0x0200,
  GamePadBtnKeyBTN_LT = 0x0400,
  GamePadBtnKeyBTN_RT = 0x0800,
  GamePadBtnKeyBTN_L3 = 0x0040,
  GamePadBtnKeyBTN_R3 = 0x0080,
  GamePadBtnKeyBTN_UP = 0x0001,
  GamePadBtnKeyBTN_DOWN = 0x0002,
  GamePadBtnKeyBTN_LEFT = 0x0004,
  GamePadBtnKeyBTN_RIGHT = 0x0008,
  GamePadBtnKeyBTN_BACK = 0x0020,
  GamePadBtnKeyBTN_START = 0x0010,
};

@class UIButton;

SWIFT_CLASS("_TtCC10WhaleCloud7GamePad6Rocker")
@interface Rocker : NSObject
@property (nonatomic, strong) UIButton * _Nonnull bg;
@property (nonatomic, strong) UIButton * _Nonnull stick;
@property (nonatomic) CGFloat rSmall;
@property (nonatomic) CGFloat rBig;
@property (nonatomic) int8_t position;
- (nonnull instancetype)initWithBg:(UIButton * _Nonnull)bg stick:(UIButton * _Nonnull)stick rSmall:(CGFloat)rSmall rBig:(CGFloat)rBig position:(int8_t)position OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10WhaleCloud18GamePadRumbleEvent")
@interface GamePadRumbleEvent : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(int32_t, JyCode, open) {
  JyCodeEVENT_SDK_INIT = 50000,
  JyCodeERR_BS_CONNECT = 40000,
  JyCodeERR_BS_CERT = 40001,
  JyCodeEVENT_BS_SUCC = 51000,
  JyCodeEVENT_BS_QUE = 51102,
  JyCodeEVENT_BS_QUE_OK = 51103,
  JyCodeERR_BS_FAIL = 41104,
  JyCodeEVENT_BS_SAVE_PROCESS = 41106,
  JyCodeEVENT_BS_CANCLE_QUE_SUCC = 51107,
  JyCodeEVENT_BS_CANCLE_QUE_FAIL = 41108,
  JyCodeEVENT_MS_OK = 52000,
  JyCodeERR_MS_SIGNIN_TIMEOUT = 42000,
  JyCodeEVENT_RTC_CONNECTED = 53000,
  JyCodeERR_RTC_CONNECT = 43000,
  JyCodeEVENT_GS_GAME_STARTED = 54000,
  JyCodeEVENT_GS_GAME_EXIT = 54001,
  JyCodeERR_GS_START_GAME = 44000,
  JyCodeERR_GS_GAME_FAIL = 44001,
  JyCodeEVENT_GAME_MODIFIED = 44002,
  JyCodeEVENT_PREALARM = 45001,
  JyCodeEVENT_ALARM = 45002,
  JyCodeEVENT_SET_LEVEL_SUCC = 45003,
  JyCodeEVENT_SET_LEVEL_FAIL = 45004,
  JyCodeEVENT_TAKENOVER = 54002,
  JyCodeEVENT_AUTH_OPT_BY_HOST = 54003,
  JyCodeEVENT_SESSION_NOT_EXSIT = 44003,
  JyCodeEVENT_HANGUP_TIME_MODIFIED = 54102,
  JyCodeEVENT_HANGUP_SUCC = 54103,
  JyCodeEVENT_HANGUP_TIME_MODIFIED_FAIL = 44102,
  JyCodeEVENT_HANGUP_FAILED = 44103,
  JyCodeEVENT_AUTH_OPT_SUCC = 54104,
  JyCodeEVENT_AUTH_OPT_FAIL = 44104,
  JyCodeEVENT_CHANGE_HANDLE_SUCC = 54105,
  JyCodeEVENT_CHANGE_HANDLE_FAIL = 44105,
  JyCodeEVENT_RESTART_GAME_SUCC = 54106,
  JyCodeEVENT_RESTART_GAME_FAIL = 44106,
  JyCodeEVENT_OTHER = 99999,
  JyCodeERR_TOO_QUICK = 88888,
  JyCodeEVENT_HAS_LINK = 60000,
  JyCodeEVENT_HAS_NO_LINK = 60001,
  JyCodeEVENT_FORWARD_CHL_CONNECTED = 70001,
  JyCodeEVENT_RUNAS_SUCC = 54107,
  JyCodeEVENT_RUNAS_FAIL = 44107,
  JyCodeEVENT_MONITOR_GET_FAIL = 44108,
  JyCodeEVNET_MONITOR_CHANGE_SUCC = 54109,
  JyCodeEVENT_MONITOR_CHANGE_FAIL = 44109,
  JyCodeEVENT_MANUAL_SAVE_SUCC = 54110,
  JyCodeEVENT_MANUAL_SAVE_FAIL = 44110,
  JyCodeWRN_WIN_SIZE_CHANGED = 30001,
  JyCodeWRN_GAME_GET_SAVE_FAIL = 30002,
  JyCodeWRN_GAME_POST_SAVE_FAIL = 30003,
  JyCodeWRN_GAME_SAVE_NOT_CHANGED = 30004,
};


SWIFT_CLASS("_TtC10WhaleCloud8KeyEvent")
@interface KeyEvent : NSObject
@property (nonatomic) NSInteger code;
@property (nonatomic) BOOL down;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC10WhaleCloud15SessionDelegate")
@interface SessionDelegate : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)respondsToSelector:(SEL _Nonnull)selector SWIFT_WARN_UNUSED_RESULT;
@end


@class NSURLSession;
@class NSURLSessionDownloadTask;
@class NSURL;

@interface SessionDelegate (SWIFT_EXTENSION(WhaleCloud)) <NSURLSessionDownloadDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didFinishDownloadingToURL:(NSURL * _Nonnull)location;
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didWriteData:(int64_t)bytesWritten totalBytesWritten:(int64_t)totalBytesWritten totalBytesExpectedToWrite:(int64_t)totalBytesExpectedToWrite;
- (void)URLSession:(NSURLSession * _Nonnull)session downloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask didResumeAtOffset:(int64_t)fileOffset expectedTotalBytes:(int64_t)expectedTotalBytes;
@end

@class NSURLSessionStreamTask;
@class NSInputStream;
@class NSOutputStream;

SWIFT_AVAILABILITY(tvos,introduced=9.0) SWIFT_AVAILABILITY(macos,introduced=10.11) SWIFT_AVAILABILITY(ios,introduced=9.0)
@interface SessionDelegate (SWIFT_EXTENSION(WhaleCloud)) <NSURLSessionStreamDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session readClosedForStreamTask:(NSURLSessionStreamTask * _Nonnull)streamTask;
- (void)URLSession:(NSURLSession * _Nonnull)session writeClosedForStreamTask:(NSURLSessionStreamTask * _Nonnull)streamTask;
- (void)URLSession:(NSURLSession * _Nonnull)session betterRouteDiscoveredForStreamTask:(NSURLSessionStreamTask * _Nonnull)streamTask;
- (void)URLSession:(NSURLSession * _Nonnull)session streamTask:(NSURLSessionStreamTask * _Nonnull)streamTask didBecomeInputStream:(NSInputStream * _Nonnull)inputStream outputStream:(NSOutputStream * _Nonnull)outputStream;
@end

@class NSURLSessionDataTask;
@class NSURLResponse;
@class NSData;
@class NSCachedURLResponse;

@interface SessionDelegate (SWIFT_EXTENSION(WhaleCloud)) <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didBecomeDownloadTask:(NSURLSessionDownloadTask * _Nonnull)downloadTask;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask willCacheResponse:(NSCachedURLResponse * _Nonnull)proposedResponse completionHandler:(void (^ _Nonnull)(NSCachedURLResponse * _Nullable))completionHandler;
@end

@class NSURLAuthenticationChallenge;
@class NSURLCredential;

@interface SessionDelegate (SWIFT_EXTENSION(WhaleCloud)) <NSURLSessionDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session didBecomeInvalidWithError:(NSError * _Nullable)error;
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (void)URLSessionDidFinishEventsForBackgroundURLSession:(NSURLSession * _Nonnull)session;
@end

@class NSURLSessionTask;
@class NSHTTPURLResponse;
@class NSURLRequest;
@class NSURLSessionTaskMetrics;

@interface SessionDelegate (SWIFT_EXTENSION(WhaleCloud)) <NSURLSessionTaskDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * _Nonnull)response newRequest:(NSURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSURLRequest * _Nullable))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task needNewBodyStream:(void (^ _Nonnull)(NSInputStream * _Nullable))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didSendBodyData:(int64_t)bytesSent totalBytesSent:(int64_t)totalBytesSent totalBytesExpectedToSend:(int64_t)totalBytesExpectedToSend;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didFinishCollectingMetrics:(NSURLSessionTaskMetrics * _Nonnull)metrics SWIFT_AVAILABILITY(tvos,introduced=10.0) SWIFT_AVAILABILITY(macos,introduced=10.12) SWIFT_AVAILABILITY(ios,introduced=10.0);
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
@end


SWIFT_CLASS("_TtC10WhaleCloud12TaskDelegate")
@interface TaskDelegate : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


typedef SWIFT_ENUM(uint8_t, TextEncodeType, open) {
  TextEncodeTypeUTF8 = 1,
  TextEncodeTypeGBK = 2,
};

@class TouchPoint;
enum Action : uint8_t;
@class NSString;

SWIFT_CLASS("_TtC10WhaleCloud10TouchEvent")
@interface TouchEvent : NSObject
@property (nonatomic, copy) NSArray<TouchPoint *> * _Nonnull points;
@property (nonatomic) uint8_t activePointerIndex;
@property (nonatomic) enum Action activePointerAct;
@property (nonatomic) uint8_t cnt;
@property (nonatomic) CGRect frame;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)toString SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(uint8_t, Action, open) {
  ActionDown = 0,
  ActionUp = 1,
  ActionMove = 2,
  ActionCancel = 3,
};


SWIFT_CLASS("_TtCC10WhaleCloud10TouchEvent10TouchPoint")
@interface TouchPoint : NSObject
@property (nonatomic, copy) NSString * _Nonnull tag;
@property (nonatomic) uint8_t index;
@property (nonatomic) float x;
@property (nonatomic) float y;
@property (nonatomic) enum Action act;
@property (nonatomic) uint8_t toolType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC10WhaleCloud15WcFeedBackEvent")
@interface WcFeedBackEvent : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_TOUCH_POINTER;)
+ (uint8_t)EVENT_TOUCH_POINTER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_KEYBOARD_BUTTON;)
+ (uint8_t)EVENT_KEYBOARD_BUTTON SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_GAMEPAD;)
+ (uint8_t)EVENT_GAMEPAD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_MOUSE_ABSOLUTE;)
+ (uint8_t)EVENT_MOUSE_ABSOLUTE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_GAMEPAD_RUMBLE;)
+ (uint8_t)EVENT_GAMEPAD_RUMBLE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_MOUSE_RELATIVE;)
+ (uint8_t)EVENT_MOUSE_RELATIVE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_CURSOR_UPDATE;)
+ (uint8_t)EVENT_CURSOR_UPDATE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_POSITION_UPDATE;)
+ (uint8_t)EVENT_POSITION_UPDATE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_INPUT;)
+ (uint8_t)EVENT_INPUT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_FILE_COPY;)
+ (uint8_t)EVENT_FILE_COPY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_CODEC_FEEDBACK;)
+ (uint8_t)EVENT_CODEC_FEEDBACK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_OPEN_URL;)
+ (uint8_t)EVENT_OPEN_URL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_UDISK;)
+ (uint8_t)EVENT_UDISK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) uint8_t EVENT_WIN_POPUP;)
+ (uint8_t)EVENT_WIN_POPUP SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) uint8_t msgType;
@property (nonatomic) uint8_t mimeType;
@property (nonatomic) uint8_t x_offset;
@property (nonatomic) uint8_t y_offset;
@property (nonatomic, copy) NSData * _Nonnull data;
@property (nonatomic) NSInteger position_x;
@property (nonatomic) NSInteger position_y;
@property (nonatomic, strong) GamePadRumbleEvent * _Nonnull gamepadEvent;
@property (nonatomic, copy) NSString * _Nonnull url;
@property (nonatomic, copy) NSString * _Nonnull winName;
@property (nonatomic, copy) NSString * _Nonnull winPath;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum Severity : uint8_t;

SWIFT_CLASS("_TtC10WhaleCloud9WcLogUtil")
@interface WcLogUtil : NSObject
+ (void)enableLogToDebugOutputWithLevel:(enum Severity)level;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(uint8_t, Severity, open) {
  SeverityLS_INFO = 4,
  SeverityLS_DEBUG = 3,
  SeverityLS_WARNING = 2,
  SeverityLS_ERROR = 1,
  SeverityLS_NONE = 0,
};



SWIFT_CLASS("_TtC10WhaleCloud13WcMouseStatus")
@interface WcMouseStatus : NSObject
@property (nonatomic) float x;
@property (nonatomic) float y;
@property (nonatomic) int8_t x_delta;
@property (nonatomic) int8_t y_delta;
@property (nonatomic) uint8_t button;
@property (nonatomic) int8_t scroll;
@property (nonatomic) CGRect frame;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)set_leftButtonWithDown:(BOOL)down;
- (void)set_RightButtonWithDown:(BOOL)down;
- (void)set_ScrollButtonWithDown:(BOOL)down;
- (void)set_scrollWithScroll:(int8_t)scroll;
@end



SWIFT_CLASS("_TtC10WhaleCloud9WebSocket")
@interface WebSocket : NSObject <NSStreamDelegate>
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@protocol WhaleCloudDelegate;
@class NSBundle;
@class UIViewController;
@class tController;

SWIFT_CLASS("_TtC10WhaleCloud10WhaleCloud")
@interface WhaleCloud : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) WhaleCloud * _Nonnull instance;)
+ (WhaleCloud * _Nonnull)instance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <WhaleCloudDelegate> _Nullable delegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setBundleCfWithBundle:(NSBundle * _Nonnull)bundle;
- (UIViewController * _Nonnull)getVideoViewControllerCf SWIFT_WARN_UNUSED_RESULT;
- (void)setWhaleDelegateCfWithWcDelegate:(id <WhaleCloudDelegate> _Nonnull)wcDelegate;
- (BOOL)sendGamepadEventCfWithPlayer:(tController * _Nonnull)player SWIFT_WARN_UNUSED_RESULT;
- (void)enableSpeakerCfOn:(BOOL)on;
- (BOOL)sendKeyBoardEventCfWithEvent:(KeyEvent * _Nonnull)event SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sendMouseEventCfWithMouseStatus:(WcMouseStatus * _Nonnull)mouseStatus SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sendTouchEventCfWithEvent:(TouchEvent * _Nonnull)event SWIFT_WARN_UNUSED_RESULT;
- (BOOL)repeatSendMouseEventCfWithMouseStatus:(WcMouseStatus * _Nonnull)mouseStatus SWIFT_WARN_UNUSED_RESULT;
- (BOOL)repeatSendKeyBoardEventCfWithEvent:(KeyEvent * _Nonnull)event SWIFT_WARN_UNUSED_RESULT;
- (BOOL)repeatSendGamepadEventCfWithPlayer:(tController * _Nonnull)player SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sdkLoadingCfWithChannelId:(NSString * _Nonnull)channelId bsUrl:(NSString * _Nonnull)bsUrl token:(NSString * _Nonnull)token sn:(NSString * _Nonnull)sn SWIFT_WARN_UNUSED_RESULT;
- (BOOL)startCfWithGameData:(NSString * _Nonnull)gameData SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getSNCf SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setServiceLevelCfWithLevel_config:(NSString * _Nonnull)level_config SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getVersionNameCf SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sendMsgToGameCfWithMsg:(NSString * _Nonnull)msg SWIFT_WARN_UNUSED_RESULT;
- (BOOL)takePlayGameCfWithGameData:(NSString * _Nonnull)gameData SWIFT_WARN_UNUSED_RESULT;
- (BOOL)reconPlayGameCfWithGameData:(NSString * _Nonnull)gameData SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hangUpCfWithHang_up_config:(NSString * _Nonnull)hang_up_config SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sethangUpTimerCfWithHang_up_config:(NSString * _Nonnull)hang_up_config SWIFT_WARN_UNUSED_RESULT;
- (BOOL)setRoomHandleCfWithHandle_config:(NSString * _Nonnull)handle_config SWIFT_WARN_UNUSED_RESULT;
- (BOOL)muteCfWithIsMute:(BOOL)isMute SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sendChangeHandleCfWithRoomKey:(NSString * _Nonnull)roomKey change:(NSString * _Nonnull)change SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sendRestartGameCfWithSaveTime:(NSString * _Nonnull)saveTime saveEnable:(NSInteger)saveEnable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)stopEngineCf SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sendRestartGameWithConfigCfWithSaveConfig:(NSString * _Nonnull)saveConfig saveTime:(NSString * _Nonnull)saveTime saveEnable:(NSInteger)saveEnable SWIFT_WARN_UNUSED_RESULT;
- (BOOL)stopEngineCfWithMsg:(NSString * _Nonnull)msg keepSession:(BOOL)keepSession SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sendTextCfWithEncodeType:(enum TextEncodeType)encodeType data:(NSArray<NSNumber *> * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (BOOL)sendRunasCfWithRun_path:(NSString * _Nonnull)run_path run_args:(NSString * _Nonnull)run_args SWIFT_WARN_UNUSED_RESULT;
- (BOOL)getMonitorNumberCf SWIFT_WARN_UNUSED_RESULT;
- (BOOL)changeMonitorCfWithMonitorID:(NSInteger)monitorID SWIFT_WARN_UNUSED_RESULT;
- (BOOL)manualSaveCfWithSaveConfig:(NSString * _Nonnull)saveConfig SWIFT_WARN_UNUSED_RESULT;
- (void)setVolumeWithVolume:(double)volume;
@end




SWIFT_PROTOCOL("_TtP10WhaleCloud18WhaleCloudDelegate_")
@protocol WhaleCloudDelegate <NSObject>
- (void)onEngineStop;
- (void)onEngineStarting;
- (void)onMonitorNumberWithNumber:(NSInteger)number;
- (void)onEngineQosWithQos:(NSDictionary<NSString *, NSString *> * _Nonnull)qos;
- (void)onEngineEventWithCode:(int32_t)code msg:(NSString * _Nonnull)msg;
- (void)onEngineErrorWithCode:(int32_t)code msg:(NSString * _Nonnull)msg;
- (void)onEngineStart:(UIViewController * _Nonnull)view;
- (void)onEngineMsgWithSessisonId:(NSString * _Nonnull)sessisonId msg:(NSString * _Nonnull)msg;
- (void)onEngineFeedbackWithEvent:(WcFeedBackEvent * _Nonnull)event;
@end


SWIFT_CLASS("_TtC10WhaleCloud15WhaleCloudParam")
@interface WhaleCloudParam : NSObject
@property (nonatomic, copy) NSString * _Nonnull gs_name;
@property (nonatomic) NSInteger queue_grade;
@property (nonatomic, copy) NSString * _Nonnull game_key;
@property (nonatomic, copy) NSString * _Nonnull save_time;
@property (nonatomic, copy) NSString * _Nonnull room_name;
@property (nonatomic, copy) NSString * _Nonnull game_args;
@property (nonatomic) NSInteger display_grade;
@property (nonatomic) BOOL able_queue;
@property (nonatomic, copy) NSString * _Nonnull start_resolution;
@property (nonatomic, copy) NSString * _Nonnull record_game_time;
@property (nonatomic, copy) NSString * _Nonnull model_name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10WhaleCloud11tController")
@interface tController : NSObject
@property (nonatomic) int16_t LX;
@property (nonatomic) int16_t LY;
@property (nonatomic) int16_t RX;
@property (nonatomic) int16_t RY;
@property (nonatomic) uint8_t player;
@property (nonatomic) uint16_t wButtons;
@property (nonatomic) uint8_t bLeftTrigger;
@property (nonatomic) uint8_t bRightTrigger;
- (nonnull instancetype)initWithPlayerNo:(uint8_t)playerNo OBJC_DESIGNATED_INITIALIZER;
- (void)setKeyWithKeyCode:(uint16_t)keyCode down:(BOOL)down;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
